NLog/NLog.Web

NLog.Web.sln, NLog.Web/IISInstanceNameLayoutRenderer.cs, NLog.Web/NLog.Web.csproj, NLog.Web/NLog.Web.nuspec, NLog.Web/Properties/AssemblyInfo.cs, NLog.Web/packages.config, appveyor.yml
Taken from NLog/NLog#484.
closes NLog/NLog#484
=> Add IIS web site name layout renderer

NLog.Web.sln, NLog.Web/LayoutRenderers/AspNetApplicationValueLayoutRenderer.cs, NLog.Web/LayoutRenderers/AspNetRequestValueLayoutRenderer.cs, NLog.Web/LayoutRenderers/AspNetSessionIDLayoutRenderer.cs, NLog.Web/LayoutRenderers/AspNetSessionValueLayoutRenderer.cs, NLog.Web/LayoutRenderers/AspNetUserAuthTypeLayoutRenderer.cs, NLog.Web/LayoutRenderers/AspNetUserIdentityLayoutRenderer.cs, NLog.Web/LayoutRenderers/IISInstanceNameLayoutRenderer.cs, NLog.Web/NLog.Web.csproj, NLog.Web/NLogHttpModule.cs, NLog.Web/Targets/Temp.cs, NLog.Web/Targets/Wrappers/AspNetBufferingTargetWrapper.cs
Move the existing targets and layout renderers from NLog.Extended
=> Move stuff from extended

NLog.Web.Tests/LayoutRenderers/AspNetSessionValueLayoutRendererTests.cs, NLog.Web/LayoutRenderers/AspNetApplicationValueLayoutRenderer.cs, NLog.Web/LayoutRenderers/AspNetItemValueLayoutRenderer.cs, NLog.Web/LayoutRenderers/AspNetRequestValueLayoutRenderer.cs, NLog.Web/LayoutRenderers/AspNetSessionValueLayoutRenderer.cs
This wan't working:
```
${aspnet-session:variable=anothervariable:culture=pl-PL} 
```
because `InvariantCulture` was used. Now using UICulture.
Supported in:
* ${aspnet-application}
* ${aspnet-request}
* ${aspnet-session}
* ${aspnet-item}
=> Added Culture tests and use current culture (can be set)

NLog.Web.Tests/DefaultHttpContextAccessorTests.cs, NLog.Web.Tests/FakeHttpContextAccessor.cs, NLog.Web.Tests/LayoutRenderers/AspNetApplicationValueLayoutRendererTests.cs, NLog.Web.Tests/LayoutRenderers/AspNetItemValueLayoutRendererTests.cs, NLog.Web.Tests/LayoutRenderers/AspNetRequestValueLayoutRendererTests.cs, NLog.Web.Tests/LayoutRenderers/AspNetSessionIDLayoutRendererTests.cs, NLog.Web.Tests/LayoutRenderers/AspNetUserAuthTypeLayoutRendererTests.cs, NLog.Web.Tests/LayoutRenderers/AspNetUserIdentityLayoutRendererTests.cs, NLog.Web.Tests/NLog.Web.Tests.csproj, NLog.Web.Tests/packages.config, NLog.Web/DefaultHttpContextAccessor.cs, NLog.Web/IHttpContextAccessor.cs, NLog.Web/LayoutRenderers/AspNetApplicationValueLayoutRenderer.cs, NLog.Web/LayoutRenderers/AspNetItemValueLayoutRenderer.cs, NLog.Web/LayoutRenderers/AspNetLayoutRendererBase.cs, NLog.Web/LayoutRenderers/AspNetRequestValueLayoutRenderer.cs, NLog.Web/LayoutRenderers/AspNetSessionIDLayoutRenderer.cs, NLog.Web/LayoutRenderers/AspNetSessionValueLayoutRenderer.cs, NLog.Web/LayoutRenderers/AspNetUserAuthTypeLayoutRenderer.cs, NLog.Web/LayoutRenderers/AspNetUserIdentityLayoutRenderer.cs, NLog.Web/NLog.Web.csproj
This is an initial commit for #20. There is still more work to be done. I just wanted to share and get some initial feedback.
fixes https://github.com/NLog/NLog.Web/issues/20
=> Introducing ASP.NET Layout Renderer base class

README.md
I think the JSON code block was improperly terminated - but there's a difference between the client-side and server-side markdown rendering, I think, so I cannot be certain without issuing the PR.
=> fix syntax of readme.md

NLog.Web.ASPNET5/project.json, NLog.Web.ASPNET5/project.lock.json
Add dotnet5.4, update to NLog 4.4 beta1 (minimal)
fixes #49
=> Add dotnet5.4 framework

NLog.Web.ASPNET5/Internal/PropertyReader.cs
Supersedes https://github.com/NLog/NLog.Web/pull/26
=> Extra null check

NLog.Web.ASPNET5/LayoutRenderers/AspNetSessionValueLayoutRenderer.cs
Prevent stackoverflowException in `${aspnet-session}` by using `HttpContext.Items`.
In case of an session issue, [ASP.NET session will log a warning](https://github.com/aspnet/Session/blob/1.0.0-rc1/src/Microsoft.AspNet.Session/DistributedSession.cs#L142). This could lead to a `StackOverflowException `.
We will prevent this by pushing and removing an item on `context.Items `
Details in https://github.com/NLog/NLog.Extensions.Logging/issues/28
Fixes https://github.com/NLog/NLog.Extensions.Logging/issues/28, fixes https://github.com/NLog/NLog.Web/issues/43
needs confirmation.
=> DNX: Prevent stackoverflowException in ${aspnet-session}

NLog.Web.ASPNET5.Tests/LayoutRenderers/AspNetRequestValueLayoutRendererTests.cs, NLog.Web.ASPNET5/LayoutRenderers/AspNetRequestValueLayoutRenderer.cs
As a response to https://github.com/NLog/NLog.Web/issues/31
I have *not* kept the old behavior for .net core.
=> Suppressing exception thrown when accessing HttpContext.Request

NLog.Web.AspNetCore/LayoutRenderers/AspNetRequestCookieLayoutRenderer.cs
Fixes https://github.com/NLog/NLog.Web/issues/96
=> Fixing missing name for ${aspnet-request-cookie}

NLog.Web.AspNetCore.Tests/LayoutRenderers/AspNetQueryStringLayoutRendererTests.cs, NLog.Web.AspNetCore/LayoutRenderers/AspNetRequestQueryStringLayoutRenderer.cs
=> support for empty 'QueryStringKeys' for ${all-querystrings{aspnet-request-querystring}

NLog.Web.AspNetCore/LayoutRenderers/AspNetEnvironmentLayoutRenderer.cs, NLog.Web.AspNetCore/LayoutRenderers/IISInstanceNameLayoutRenderer.cs
supersedes https://github.com/NLog/NLog.Web/pull/121
=> fix ${iis-site-name} for ASP.NET Core, move IHostingEnvironment.EnvironmentName to ${aspnet-environment}

NLog.Web.AspNetCore/LayoutRenderers/AspNetLayoutRendererBase.cs
See https://github.com/NLog/NLog/issues/2064
=> Improve performance with many threads

NLog.Web.AspNetCore/LayoutRenderers/AspNetEnvironmentLayoutRenderer.cs, NLog.Web.AspNetCore/LayoutRenderers/AspNetLayoutRendererBase.cs, NLog.Web.AspNetCore/LayoutRenderers/IISInstanceNameLayoutRenderer.cs
Fixes https://github.com/NLog/NLog.Web/issues/134
=> small performance improvements for ServiceLocator

NLog.Web.AspNetCore/LayoutRenderers/AspNetUserAuthTypeLayoutRenderer.cs, NLog.Web.AspNetCore/LayoutRenderers/AspNetUserIdentityLayoutRenderer.cs
=> ignore ObjectDisposedException in aspnet-user renderers

NLog.Web.AspNetCore/LayoutRenderers/AspNetUserIsAuthenticatedLayoutRenderer.cs, NLog.Web/NLog.Web.csproj
fixes https://github.com/NLog/NLog.Web/issues/135
=> added ${aspnet-user-isAuthenticated}

NLog.Web.AspNetCore/NLog.Web.AspNetCore.csproj
Hi,
I scanned Nlog.Web.AspNetCore using [dotnet retire](https://github.com/RetireNet/dotnet-retire) and found use of a vulnerable dependency. This PR bumps the package that brings this dependency in.
Dependency chain resulting in use [of vulnerable dependency `System.Text.Encodings.Web/4.0.0`](https://github.com/dotnet/announcements/issues/12) :
[Microsoft.AspNetCore.Routing.Abstractions/1.0.3](https://www.nuget.org/packages/Microsoft.AspNetCore.Routing.Abstractions/1.0.3)
=> 
[Microsoft.AspNetCore.Http.Abstractions/1.0.2](https://www.nuget.org/packages/Microsoft.AspNetCore.Http.Abstractions/1.0.2)
=>
[System.Text.Encodings.Web/4.0.0](https://www.nuget.org/packages/System.Text.Encodings.Web/4.0.0)
=> Update vulnerable dependency

NLog.Web.AspNetCore.Tests/NLog.Web.AspNetCore.Tests.csproj, NLog.Web.AspNetCore/NLog.Web.AspNetCore.csproj, test_aspnetcore.bat
I think this fixes #151 without breaking it, but I could not run the tests on the machine I'm currently on because they're only target full framework.
=> Run test for asp.net core on full and core framework, fix unit test build

NLog.Web.AspNetCore.Tests/LayoutRenderers/AspNetRequestUrlRendererTests.cs, NLog.Web.AspNetCore/LayoutRenderers/AspNetRequestUrlRenderer.cs
Currently the AspNetRequestUrlRenderer doesn't let you do relative urls
e.g. /somepath?q=stuff
If you set *IncludeHost=false* you end up with the scheme (http://) included
http:///somepath?q=stuff
I've added an IncludeScheme option so that the "http://" part can be excluded too.
=> Add IncludeScheme option to ${aspnet-request-url}

NLog.Web.AspNetCore.Tests/NLog.Web.AspNetCore.Tests.csproj, NLog.Web.AspNetCore.Tests/TestBase.cs, NLog.Web.AspNetCore/LayoutRenderers/AssemblyVersionLayoutRenderer.cs, NLog.Web.AspNetCore/NLog.Web.AspNetCore.csproj
fixes https://github.com/NLog/NLog.Web/issues/168
=> ASP.NET Core 2 support

NLog.Web.AspNetCore/LayoutRenderers/AspNetLayoutRendererBase.cs
fixes https://github.com/NLog/NLog.Web/issues/157
=> Fix IHttpContextAccessor warning

NLog.Web.AspNetCore.Tests/AspNetCoreTests.cs, NLog.Web.AspNetCore.Tests/NLog.Web.AspNetCore.Tests.csproj, NLog.Web.AspNetCore/AspNetExtensions.cs, NLog.Web.AspNetCore/Internal/ServiceLocator.cs, NLog.Web.AspNetCore/NLog.Web.AspNetCore.csproj
Add UseNLog, Update dependency, Obsolete AddNLogWeb, Prepare for registering services
fixes #177 , fixes #181 , fixes https://github.com/NLog/NLog.Web/issues/172
supersedes https://github.com/NLog/NLog.Web/pull/173
=> Add UseNLog for ASP.NET Core 2

NLog.Web.AspNetCore.Tests/AspNetCoreTests.cs, NLog.Web.AspNetCore/AspNetExtensions.cs, NLog.Web.AspNetCore/Internal/ServiceLocator.cs, NLog.Web.AspNetCore/LayoutRenderers/AspNetLayoutRendererBase.cs, NLog.Web.AspNetCore/LayoutRenderers/AspNetSessionValueLayoutRenderer.cs, NLog.Web.AspNetCore/NLog.Web.AspNetCore.csproj, NLog.Web.AspNetCore/NLogAspNetCoreOptions.cs, NLog.Web.AspNetCore/Properties/AssemblyInfo.cs
Register HttpContextAccessor by default, added NLogAspNetCoreOptions
fixes #73
=> Register HttpContextAccessor by default

NLog.Web.AspNetCore.Tests/AspNetCoreTests.cs, NLog.Web.AspNetCore/AspNetExtensions.cs
No need for 
```xml
<extensions>
<add assembly="NLog.Web.AspNetCore"/>
</extensions>
```
any more.
usage of `.UseNLog()` required
fixes https://github.com/NLog/NLog.Web/issues/187
=> Auto register NLog.Web.AspNetCore (ASP.NET 2 only)

NLog.Web.AspNetCore/AspNetExtensions.cs, NLog.Web.AspNetCore/NLogBuilder.cs
closes https://github.com/NLog/NLog.Web/issues/185
=> add ConfigureNLog on ILoggingBuilder

NLog.Web.AspNetCore/AspNetExtensions.cs, NLog.Web.AspNetCore/NLogBuilder.cs
fixes https://github.com/NLog/NLog.Web/issues/200
=> Fix ${callsite} in Asp.net core 2

NLog.Web.AspNetCore/AspNetExtensions.cs
So config made before UseNLog is still applied and Microsoft's addConsole is also working
fixes https://github.com/NLog/NLog.Web/issues/199
needed for backwardsomp.
=> Register NLogProvider instead of NLogFactory

NLog.Web.AspNetCore/NLog.Web.AspNetCore.csproj, NLog.Web.AspNetCore/NLogBuilder.cs
Fixes https://github.com/NLog/NLog.Web/issues/206
=> Fix ${callsite} from configure

NLog.Web.AspNetCore/LayoutRenderers/AssemblyVersionLayoutRenderer.cs, NLog.Web.AspNetCore/NLog.Web.AspNetCore.csproj
fixes https://github.com/NLog/NLog.Web/issues/222 and fixes https://github.com/NLog/NLog/issues/2428
thanks @snakefoot!
=> Fix assembly-version

NLog.Web.AspNetCore.Tests/NLog.Web.AspNetCore.Tests.csproj, NLog.Web.AspNetCore.Tests/TestBase.cs, NLog.Web.AspNetCore/AspNetExtensions.cs, NLog.Web.AspNetCore/NLog.Web.AspNetCore.csproj, NLog.Web.AspNetCore/NLogBuilder.cs
Fixes https://github.com/NLog/NLog.Web/issues/208
+ introduced ASP_NET_CORE1 + ASP_NET_CORE2 constants
=> .NET 4.6.1 + ASP.NET Core 2 support

NLog.Web.AspNetCore/AspNetExtensions.cs, NLog.Web.AspNetCore/DependencyInjection/ServiceLocator.cs, NLog.Web.AspNetCore/LayoutRenderers/AspNetEnvironmentLayoutRenderer.cs, NLog.Web.AspNetCore/LayoutRenderers/AspNetLayoutRendererBase.cs, NLog.Web.AspNetCore/LayoutRenderers/IISInstanceNameLayoutRenderer.cs
to support other DI systems
fixes https://github.com/NLog/NLog.Web/issues/227
=> Made ServiceLocator public

NLog.Web.AspNetCore/NLogBuilder.cs
See https://github.com/NLog/NLog.Web/issues/229
=> Better hide assemblies for ${callsite}

NLog.Web.AspNetCore/LayoutRenderers/AssemblyVersionLayoutRenderer.cs, NLog.Web.AspNetCore/NLog.Web.AspNetCore.csproj
=> Updated dependencies

NLog.Web.AspNetCore.Tests/AspNetCoreTests.cs, NLog.Web.AspNetCore/AspNetExtensions.cs, NLog.Web.AspNetCore/NLog.Web.AspNetCore.csproj, NLog.Web.AspNetCore/NLogBuilder.cs
Resolves #242 (Updates to latest NLog.Extensions.Logging ver. 1.0.0-rc07 and also resolves #239)
=> Use LogManager.LoadConfiguration + RC3

NLog.Web.AspNetCore.Tests/AspNetCoreTests.cs, NLog.Web.AspNetCore.Tests/NLog.Web.AspNetCore.Tests.csproj, NLog.Web.AspNetCore/AspNetExtensions.cs
No longer need to add this for NetCoreApp1:
```
<extensions>
<add assembly="NLog.Web.AspNetCore"/>
</extensions>
```
Guess the wiki-page has to be updated.
=> Automatically register NLog.Web LayoutRenders for NetCoreApp1

NLog.Web.AspNetCore.Tests/Properties/AssemblyInfo-test.cs, NLog.Web.Tests/Properties/AssemblyInfo-test.cs, appveyor.yml
Configured xunit to `DisableTestParallelization` (Attempt to make tests less flaky)
And discovered removing `version` affected the build-names:
https://ci.appveyor.com/project/nlog/nlog-web/history
=> Configured xunit DisableTestParallelization to make tests more stable

NLog.Web.AspNetCore/AspNetExtensions.cs, NLog.Web.AspNetCore/Internal/RequestAccessorExtension.cs
`UseNLog` together with `ConfigureNLog` will generate duplicate logging (builder.AddNLog will register a second time). 
See also:
https://stackoverflow.com/questions/33613971/nlog-logs-error-twice-in-same-file
https://stackoverflow.com/questions/42589841/how-can-i-stop-nlog-from-double-logging
I guess registering an ILoggerFactory as singleton (That ignores any calls to `AddProvider`) would also solve the issue (Making it more difficult to configure wrong). See also #235
=> ConfigureNLog should not be used together with UseNLog

NLog.Web.AspNetCore/AspNetExtensions.cs, NLog.Web.AspNetCore/NLogBuilder.cs, examples/ASP.NET Core 2/Visual Studio 2017/ASP.NET Core 2 - VS2017/Program.cs
unless the DLL has been loaded.
Resolves #267 + Resolves #264 
The example project was cheating as it had a direct reference to "NLog.Web.AspNetCore". After removing project-reference and using nuget-package, then it pre-loaded differently.
=> NLogBuilder is needed, because DLL autoload doesn't work

NLog.Web.AspNetCore/AspNetExtensions.cs, NLog.Web.AspNetCore/NLog.Web.AspNetCore.csproj
NLog.Extensions.Logging ver. 1.0.1 now handles everything in its NLogLoggerProvider.
And also corrected obsolete notifications for ConfigureNLog to match the Wiki
=> Removed explicit registration of hidden assemblies for callsite handling

NLog.Web.AspNetCore/AspNetExtensions.cs, NLog.Web.AspNetCore/Internal/ServiceLocator.cs
=> Added public method to configure the NLog ServiceLocator

NLog.Web.AspNetCore/AspNetExtensions.cs
Guessing that Assembly lookup during startup is not welcome. Trying to resolve #281 
Another example of assembly lookup during startup is failing for ServiceFabric: https://github.com/quartznet/quartznet/issues/619 (Though here the bug is in `SerilogLogProvider.IsLoggerAvailable`)
=> Avoid assembly lookup on static class initialization

NLog.Web.AspNetCore.Tests/FakeHttpContextAccessor.cs, NLog.Web.AspNetCore.Tests/LayoutRenderers/AspNetCookieLayoutRendererTests.cs, NLog.Web.AspNetCore.Tests/LayoutRenderers/TestInvolvingAspNetHttpContext.cs
Pre-work for #294.
* Creates a 'real' and not mocked HttpContext for use in ASP.NET Core unit tests
* Switched CookieLayoutRenderer to use this 'real' HttpContext
* Added comments about what multi-valued cookies are and their origins from Classic ASP
* Corrected incorrect namings, typos, and spacing
=> CookieLayoutRenderer unit test clean up

NLog.Web.AspNetCore.Tests/LayoutRenderers/AssemblyVersionLayoutRendererTests.cs, NLog.Web.AspNetCore.Tests/NLog.Web.AspNetCore.Tests.csproj, NLog.Web.AspNetCore/LayoutRenderers/AssemblyVersionLayoutRenderer.cs, NLog.Web.AspNetCore/NLog.Web.AspNetCore.csproj, NLog.Web.Tests/NLog.Web.Tests.csproj, NLog.Web.Tests/Properties/AssemblyInfo-test.cs, NLog.Web.Tests/packages.NLog.Web.Tests.config, NLog.Web/NLog.Web.csproj, NLog.Web/packages.NLog.Web.config, examples/ASP.NET 4.6.1/Visual Studio 2017/ASP.NET 4.6.1 - VS2017/ASP.NET 4.6.1 - VS2017.csproj, examples/ASP.NET 4.6.1/Visual Studio 2017/ASP.NET 4.6.1 - VS2017/Controllers/HomeController.cs, examples/ASP.NET 4.6.1/Visual Studio 2017/ASP.NET 4.6.1 - VS2017/Global.asax.cs, examples/ASP.NET 4.6.1/Visual Studio 2017/ASP.NET 4.6.1 - VS2017/Properties/AssemblyInfo.cs, examples/ASP.NET 4.6.1/Visual Studio 2017/ASP.NET 4.6.1 - VS2017/packages.config, examples/ASP.NET Core 2/Visual Studio 2017/ASP.NET Core 2 - VS2017/ASP.NET Core 2 - VS2017.csproj
Fixes #293 and NLog/NLog#2783.
Tested with unit tests, and example projects for ASP.NET Core 2.x and .NET Framework 4.6.
NOTE: merging this will mean NLog 4.5.7 is now required as minimum for NLog.Web to work correctly.
=> Inherits AssemblyVersionLayoutRenderer from NLog implementation (ASP.NET + ASP.NET Core)

appveyor.yml
fixes:
> Attempting to gather dependency information for package 'OpenCover.4.6.519' with respect to project 'C:\projects\nlogweb', targeting 'Any,Version=v0.0'
Gathering dependency information took 251.85 ms
Attempting to resolve dependencies for package 'OpenCover.4.6.519' with DependencyBehavior 'Lowest'
Unable to find package 'NLog.Web'. Existing packages must be restored before performing an install or update.
Command exited with code 1
=> Fix Opencover install

NLog.Web.AspNetCore.Tests/LayoutRenderers/AspNetApplicationValueLayoutRendererTests.cs, NLog.Web.AspNetCore.Tests/LayoutRenderers/AspNetItemValueLayoutRendererTests.cs, NLog.Web.AspNetCore.Tests/LayoutRenderers/AspNetRequestValueLayoutRendererTests.cs, NLog.Web.AspNetCore.Tests/LayoutRenderers/AspNetSessionValueLayoutRendererTests.cs, NLog.Web.AspNetCore/Internal/PropertyReader.cs, NLog.Web.AspNetCore/Internal/RequestAccessorExtension.cs, NLog.Web.AspNetCore/LayoutRenderers/AspNetItemValueLayoutRenderer.cs, NLog.Web.AspNetCore/LayoutRenderers/AspNetLayoutRendererBase.cs, NLog.Web.AspNetCore/LayoutRenderers/AspNetSessionValueLayoutRenderer.cs, NLog.Web.AspNetCore/NLog.Web.AspNetCore.csproj, NLog.Web.Tests/NLog.Web.Tests.csproj, NLog.Web.Tests/packages.NLog.Web.Tests.config
Could also be nice to remove "Microsoft.AspNetCore.Http", but it would require removal of `RegisterHttpContextAccessor`
=> Removed dependency on Microsoft.AspNetCore.Http.Extensions

NLog.Web.AspNetCore.Tests/LayoutRenderers/AspNetCookieLayoutRendererTests.cs, NLog.Web.AspNetCore.Tests/LayoutRenderers/AspNetQueryStringLayoutRendererTests.cs, NLog.Web.AspNetCore/DefaultHttpContextAccessor.cs, NLog.Web.AspNetCore/LayoutRenderers/AspNetApplicationValueLayoutRenderer.cs, NLog.Web.AspNetCore/LayoutRenderers/AspNetItemValueLayoutRenderer.cs, NLog.Web.AspNetCore/LayoutRenderers/AspNetLayoutRendererBase.cs, NLog.Web.AspNetCore/LayoutRenderers/AspNetRequestContentTypeLayoutRenderer.cs, NLog.Web.AspNetCore/LayoutRenderers/AspNetRequestCookieLayoutRenderer.cs, NLog.Web.AspNetCore/LayoutRenderers/AspNetRequestHostLayoutRenderer.cs, NLog.Web.AspNetCore/LayoutRenderers/AspNetRequestHttpMethodRenderer.cs, NLog.Web.AspNetCore/LayoutRenderers/AspNetRequestIpLayoutRenderer.cs, NLog.Web.AspNetCore/LayoutRenderers/AspNetRequestQueryStringLayoutRenderer.cs, NLog.Web.AspNetCore/LayoutRenderers/AspNetRequestReferrerRenderer.cs, NLog.Web.AspNetCore/LayoutRenderers/AspNetRequestUrlRenderer.cs, NLog.Web.AspNetCore/LayoutRenderers/AspNetRequestValueLayoutRenderer.cs, NLog.Web.AspNetCore/LayoutRenderers/AspNetRequestuseragent.cs, NLog.Web.AspNetCore/LayoutRenderers/AspNetSessionIdLayoutRenderer.cs, NLog.Web.AspNetCore/LayoutRenderers/AspNetSessionValueLayoutRenderer.cs, NLog.Web.AspNetCore/LayoutRenderers/AspNetTraceIdentifierLayoutRenderer.cs, NLog.Web.AspNetCore/LayoutRenderers/AspNetUserAuthTypeLayoutRenderer.cs, NLog.Web.AspNetCore/LayoutRenderers/AspNetUserIdentityLayoutRenderer.cs, NLog.Web.AspNetCore/LayoutRenderers/AspNetUserIsAuthenticatedLayoutRenderer.cs
=> Better missing httpcontext reporting & Skip null-check of HttpContextAccessor.HttpContext in DoAppend 

NLog.Web.AspNetCore.Tests/LayoutRenderers/AspNetCookieLayoutRendererTests.cs, NLog.Web.AspNetCore.Tests/NLog.Web.AspNetCore.Tests.csproj, NLog.Web.AspNetCore/LayoutRenderers/AspNetLayoutMultiValueRendererBase.cs, NLog.Web.AspNetCore/LayoutRenderers/AspNetRequestCookieLayoutRenderer.cs, NLog.Web.AspNetCore/LayoutRenderers/AspNetRequestQueryStringLayoutRenderer.cs
Make ItemSeparator and ValueSeparator layoutable  for ${aspnet-request-querystring} and ${aspnet-request-cookie}
=> ${aspnet-request-querystring} and ${aspnet-request-cookie}): Make separators layoutable

NLog.Web.AspNetCore.Tests/LayoutRenderers/AspNetRequestValueLayoutRendererTests.cs, NLog.Web.AspNetCore/LayoutRenderers/AspNetAppBasePathLayoutRenderer.cs, NLog.Web.AspNetCore/LayoutRenderers/AspNetApplicationValueLayoutRenderer.cs, NLog.Web.AspNetCore/LayoutRenderers/AspNetEnvironmentLayoutRenderer.cs, NLog.Web.AspNetCore/LayoutRenderers/AspNetItemValueLayoutRenderer.cs, NLog.Web.AspNetCore/LayoutRenderers/AspNetMvcActionRenderer.cs, NLog.Web.AspNetCore/LayoutRenderers/AspNetMvcControllerRenderer.cs, NLog.Web.AspNetCore/LayoutRenderers/AspNetRequestContentTypeLayoutRenderer.cs, NLog.Web.AspNetCore/LayoutRenderers/AspNetRequestCookieLayoutRenderer.cs, NLog.Web.AspNetCore/LayoutRenderers/AspNetRequestFormLayoutRenderer.cs, NLog.Web.AspNetCore/LayoutRenderers/AspNetRequestHostLayoutRenderer.cs, NLog.Web.AspNetCore/LayoutRenderers/AspNetRequestHttpMethodRenderer.cs, NLog.Web.AspNetCore/LayoutRenderers/AspNetRequestIpLayoutRenderer.cs, NLog.Web.AspNetCore/LayoutRenderers/AspNetRequestQueryStringLayoutRenderer.cs, NLog.Web.AspNetCore/LayoutRenderers/AspNetRequestReferrerRenderer.cs, NLog.Web.AspNetCore/LayoutRenderers/AspNetRequestUrlRenderer.cs, NLog.Web.AspNetCore/LayoutRenderers/AspNetRequestValueLayoutRenderer.cs, NLog.Web.AspNetCore/LayoutRenderers/AspNetRequestuseragent.cs, NLog.Web.AspNetCore/LayoutRenderers/AspNetSessionIdLayoutRenderer.cs, NLog.Web.AspNetCore/LayoutRenderers/AspNetSessionValueLayoutRenderer.cs, NLog.Web.AspNetCore/LayoutRenderers/AspNetTraceIdentifierLayoutRenderer.cs, NLog.Web.AspNetCore/LayoutRenderers/AspNetUserAuthTypeLayoutRenderer.cs, NLog.Web.AspNetCore/LayoutRenderers/AspNetUserIdentityLayoutRenderer.cs, NLog.Web.AspNetCore/LayoutRenderers/AspNetUserIsAuthenticatedLayoutRenderer.cs, NLog.Web.AspNetCore/LayoutRenderers/AspNetWebRootPathLayoutRenderer.cs, NLog.Web.AspNetCore/LayoutRenderers/AssemblyVersionLayoutRenderer.cs, NLog.Web.AspNetCore/LayoutRenderers/IISInstanceNameLayoutRenderer.cs
When using AsyncWrapper then logger-threads will be able to precalculate-layouts concurrently without waiting for Target-lock.
- ${aspnet-request-url} now renders directly to StringBuilder
- ${aspnet-request} now also checks HasFormContentType. See also #322 (Also enabled unit tests for NetCore)
=> Added ThreadSafe-attribute for LayoutRenderer to optimize async Precalculate

NLog.Web.AspNetCore.Tests/LayoutRenderers/AspNetRequestFormLayoutRendererTests.cs, NLog.Web.AspNetCore.Tests/LayoutRenderers/AspNetTraceIdentifierRendererTests.cs, NLog.Web.AspNetCore/LayoutRenderers/AspNetTraceIdentifierLayoutRenderer.cs, NLog.Web.Tests/NLog.Web.Tests.csproj, NLog.Web/NLog.Web.csproj
Attempt to resolve #328 
Extracted from [HttpWorkerRequest.RequestTraceIdentifier](https://docs.microsoft.com/dotnet/api/system.web.httpworkerrequest.requesttraceidentifier). Requires IIS ETW feature enabled: https://docs.microsoft.com/en-us/iis/configuration/system.webServer/httpTracing/ (IIS7 - Win2008)
=> aspnet-traceidentifier: Support for ASP.NET (non-core) - requires IIS ETW

NLog.Web.AspNetCore/LayoutRenderers/AspNetRequestContentTypeLayoutRenderer.cs, NLog.Web/NLog.Web.csproj
=> ${aspnet-request-contenttype}  for NLog.Web

NLog.Web.AspNetCore.Tests/NLog.Web.AspNetCore.Tests.csproj, NLog.Web.AspNetCore/AspNetExtensions.cs, NLog.Web.AspNetCore/NLog.Web.AspNetCore.csproj
Updated to AspNetCore ver. 2.1 that has Long-Term-Support (LTS)
=> Register WebHost configuration with ${configsetting} and LoggingProvider-options

examples/ASP.NET Core 2/Visual Studio 2017/ASP.NET Core 2 - VS2017/ASP.NET Core 2 - VS2017.csproj, examples/ASP.NET Core 2/Visual Studio 2017/ASP.NET Core 2 - VS2017/Program.cs, examples/ASP.NET Core 2/Visual Studio 2017/ASP.NET Core 2 - VS2017/Startup.cs
Resolves #329 
Also updated Wiki: https://github.com/NLog/NLog.Web/wiki/Getting-started-with-ASP.NET-Core-2 (NetCore2 became obsolete October 2018)
=> Updated ASP.NET Core 2 example to netcoreapp2.1

NLog.Web.AspNetCore.Tests/LayoutRenderers/AspNetRequestPostedBodyTests.cs, NLog.Web.AspNetCore.Tests/LayoutRenderers/LayoutRenderersTestBase.cs, NLog.Web.AspNetCore.Tests/NLog.Web.AspNetCore.Tests.csproj, NLog.Web.AspNetCore/AspNetExtensions.cs, NLog.Web.AspNetCore/LayoutRenderers/AspNetRequestPostedBody.cs, NLog.Web.AspNetCore/NLog.Web.AspNetCore.csproj, appveyor.yml, build_aspnet.bat, build_aspnetcore.bat
Trying to resolve `A non-empty request body is required.`  where NLog reads the body before it actually have been processed. (Making it impossible for AspNetCore-engine to read the Body-payload afterwards).
See also #399 and https://github.com/NLog/NLog/issues/3273
I guess the documentation should be updated about it can give an overhead when running on AspNetCore, because it by default is not buffering HttpRequest-Body. Adding this to the logging output will give a performance-penalty in extra allocations (`EnableRewind` / `EnableBuffering`).
Also if wanting to be completely sure that HttpRequest-Body can be logged, then it is probably recommended that the AspNetCore-application itself ensures that  (`EnableRewind` / `EnableBuffering`) is performed at the right time (before the Body has …
=>  AspNetRequestPostedBody - Check ContentLength before using Body   + Added MaxContentLength (default 30Kib) + update build script

appveyor.yml
VersionSuffix should also apply for NLog.Web-build
=> Fix AppVeyor build for NLog.Web on master branch

examples/ASP.NET Core 2/Visual Studio 2017/ASP.NET Core 2 - VS2017/Controllers/HomeController.cs, examples/ASP.NET Core 2/Visual Studio 2017/ASP.NET Core 2 - VS2017/Models/MessageModel.cs, examples/ASP.NET Core 2/Visual Studio 2017/ASP.NET Core 2 - VS2017/Views/Home/Contact.cshtml, src/Shared/LayoutRenderers/AspNetRequestPostedBody.cs
+ update example
fixes https://github.com/NLog/NLog.Web/issues/429
=> Fix NotSupportedException with ${aspnet-request-posted-body} 

src/NLog.Web.AspNetCore/AspNetExtensions.cs, src/NLog.Web.AspNetCore/NLog.Web.AspNetCore.csproj
See also https://github.com/NLog/NLog.Extensions.Logging/pull/325
Requires release of NLog.Extension.Logging 1.5.4
=> Fixed double logging mixing UseNLog with AddNLog

src/Shared/LayoutRenderers/AspNetRequestHeadersLayoutRenderer.cs, tests/Shared/LayoutRenderers/AspNetRequestHeadersLayoutRendererTests.cs
fixes https://github.com/NLog/NLog.Web/issues/355
=> Added ASP.NET + ASP.NET Core layout renderer for rendering headers

src/NLog.Web.AspNetCore/AspNetExtensions.cs
Reverting #257. Since it will no longer generate double logging after #459 
Also fixed `ILoggingBuilder.ConfigureNLog()`-methods so they can work alone without `IHostBuilder.UseNLog()`.
See also: https://github.com/aspnet/AspNetCore.Docs/issues/14554
=> Removed obsolete-attribute from ConfigureNLog-methods for ILoggingBuilder

src/NLog.Web.AspNetCore/AspNetExtensions.cs
Made ConfigureNLog-methods obsolete again, since they are not fluent. Sorry about the noise. Didn't see they were broken, and failed to follow NetCore3-Api-Standard.
=> AddNLog-methods for ILoggingBuilder

src/NLog.Web.AspNetCore/AspNetExtensions.cs
IHostBuilder AddNLog attempt to setup ConfigSettingLayoutRenderer early
Increase the chance that fluent configuration will work.
=> Let IHostBuilder AddNLog work correctly with ${configsetting}

src/NLog.Web.AspNetCore/AspNetExtensions.cs
Bug was introduced in NLog.Web.AspNetCore ver. 4.8.5 by #459
Also updated the obsolete-descriptions
=>  Fixed bug introduced with IServiceCollection.Replace. Instead use TryAddEnumerable

src/NLog.Web.AspNetCore/AspNetExtensions.cs
Port of https://github.com/NLog/NLog.Web/pull/485 as hotfix
=> Fixed: Mixing AddDebug() with a file based NLog configuration no longer works

src/NLog.Web.AspNetCore/AspNetExtensions.cs, src/NLog.Web.AspNetCore/LayoutRenderers/AspNetEnvironmentLayoutRenderer.cs, src/NLog.Web.AspNetCore/NLog.Web.AspNetCore.csproj, src/Shared/LayoutRenderers/AspNetAppBasePathLayoutRenderer.cs, src/Shared/LayoutRenderers/AspNetLayoutRendererBase.cs, src/Shared/LayoutRenderers/AspNetRequestPostedBody.cs, src/Shared/LayoutRenderers/AspNetWebRootPathLayoutRenderer.cs, src/Shared/LayoutRenderers/IISInstanceNameLayoutRenderer.cs, tests/NLog.Web.AspNetCore.Tests/AspNetCoreTests.cs, tests/NLog.Web.AspNetCore.Tests/NLog.Web.AspNetCore.Tests.csproj, tests/Shared/LayoutRenderers/AspNetQueryStringLayoutRendererTests.cs, tests/Shared/LayoutRenderers/AspNetRequestHeadersLayoutRendererTests.cs, tests/Shared/LayoutRenderers/AspNetRequestValueLayoutRendererTests.cs, tests/Shared/LayoutRenderers/LayoutRenderersTestBase.cs, tests/Shared/LayoutRenderers/TestInvolvingAspNetHttpContext.cs, tests/Shared/TestBase.cs
Updated dependencies:
```xml
<ItemGroup Condition=" '$(TargetFramework)' == 'netcoreapp3.0' ">
<FrameworkReference Include="Microsoft.AspNetCore.App" />
</ItemGroup>
```
See also: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/metapackage-app?view=aspnetcore-3.0
=> Support ASP.NET Core 3

src/NLog.Web.AspNetCore/NLog.Web.AspNetCore.csproj
See also:
```
NU1607: Version conflict detected for Microsoft.AspNetCore.Hosting.Abstractions. Reference the package directly from the project to resolve this issue.
MyWebAPIProject (>= 1.0.0) -> NLog.Web.AspNetCore (>= 4.8.6) -> Microsoft.AspNetCore.Hosting.Abstractions (>= 2.1.1)
MyWebAPIProject (>= 1.0.0) -> Microsoft.AspNetCore.App (>= 2.1.0) -> Microsoft.AspNetCore.Hosting.Abstractions (>= 2.1.0).
```
From: https://stackoverflow.com/questions/58722743/how-to-fix-msbuild-error-nu1607-version-conflict-detected
=> Updated dependencies to NET Core ver. 2.1 vanilla

src/Shared/LayoutRenderers/AspNetTraceIdentifierLayoutRenderer.cs, tests/Shared/LayoutRenderers/AspNetTraceIdentifierRendererTests.cs
This is what's used in ASP .NET Core 3 templates showing Request Id. Should do the same for consistency.
Resolves #523
See also: https://github.com/dotnet/aspnetcore/blob/2e4274cb67c049055e321c18cc9e64562da52dcf/src/Mvc/Mvc.Core/src/Infrastructure/DefaultProblemDetailsFactory.cs#L90
=> aspnet-traceidentifier should automatically check Activity.Current.Id for AspNetCore3

CHANGELOG.MD, README.md, src/NLog.Web.AspNetCore/AspNetExtensions.cs, src/NLog.Web.AspNetCore/NLog.Web.AspNetCore.csproj, src/NLog.Web.AspNetCore/NLogAspNetCoreOptions.cs, src/NLog.Web/NLog.Web.csproj, src/NLog.Web/Properties/AssemblyInfo.cs, src/Shared/Enums/AspNetRequestLayoutOutputFormat.cs, src/Shared/Internal/PropertyReader.cs, src/Shared/LayoutRenderers/AspNetAppBasePathLayoutRenderer.cs, src/Shared/LayoutRenderers/AspNetTraceIdentifierLayoutRenderer.cs, tests/NLog.Web.AspNetCore.Tests/NLog.Web.AspNetCore.Tests.csproj, tests/NLog.Web.Tests/NLog.Web.Tests.csproj, tests/Shared/LayoutRenderers/AspNetTraceIdentifierRendererTests.cs
Think we should release ver. 4.9.1 with NLog.Extension.Logging 1.6.2 and NLog 4.6.8, before upgrading to NLog 4.7
Have not yet bumped version number in this PR (Incase you have other items to merge before release)
=> NLog.AspNetCore ver. 4.9.1

examples/ASP.NET Core 3/ASP.NET Core 3 - VS2019/Controllers/ApiController.cs, examples/ASP.NET Core 3/ASP.NET Core 3 - VS2019/Startup.cs
=> Added API demo case for ASP.NET Core 3 + with  context.Request.EnableBuffering(); fix

examples/ASP.NET Core 2/Visual Studio 2017/ASP.NET Core 2 - VS2017/Program.cs, examples/ASP.NET Core 3/ASP.NET Core 3 - VS2019/Program.cs, src/NLog.Web.AspNetCore/Config/SetupBuilderExtensions.cs, src/NLog.Web.AspNetCore/Config/SetupExtensionsBuilderExtensions.cs, tests/NLog.Web.AspNetCore.Tests/AspNetCoreTests.cs
Now you can do this in NetCore3:
```c#
var logger = NLog.LogManager.Setup().LoadConfigurationFromAppSettings().GetCurrentClassLogger();
```
And it replaces this for NetCore3 (Could consider making it obsolete):
```c#
var logger = NLog.Web.NLogBuilder.ConfigureNLog("nlog.config").GetCurrentClassLogger();
```
And also configures ${configsetting} and also checks appsetting.json if it contains a NLog-section with NLog config. But if none found, then NLog automatic load of NLog.config takes over.
For NetCore2 then one can do this instead of `NLogBuilder.ConfigureNLog`:
```c#
var builder = new ConfigurationBuilder()
.SetBasePath(basePath ?? Directory.GetCurrentDirectory())
.AddJsonFile("appsettings.json", optional: false, reloadOnChange: true)
.AddJsonFile($"appsettings.{environment}.json", …
```
=> LogManager.Setup() - LoadConfigurationFromAppSettings

src/NLog.Web.AspNetCore/LayoutRenderers/SessionValueType.cs, src/Shared/Internal/HttpContextExtensions.cs, src/Shared/LayoutRenderers/AspNetSessionValueLayoutRenderer.cs, tests/Shared/LayoutRenderers/AspNetSessionValueLayoutRendererTests2.cs
see https://stackoverflow.com/questions/62054400/can-the-nlog-aspnet-sessionvariable-intid-renderer-extract-display-integers-f/62054553#62054553
I think the only solution here is to add a type option to the renderer. What do you think @snakefoot ?
(If it's 4 bytes long, we only know it **could** be an int)
PS: these are the extensions in ASP.NET Core:
```c#
namespace Microsoft.AspNetCore.Http
{
public static class SessionExtensions
{
public static void SetInt32(this ISession session, string key, int value)
{
var bytes = new byte[]
{
(byte)(value >> 24),
(byte)(0xFF & (value >> 16)),
(byte)(0xFF & (value >> 8)),
(byte)(0xFF & value)
};
session.Set(key, bytes);
}
public static int? GetInt32(this ISession session, string key)
{
var data = session.Get(key);
if (data == null || data.Length < …
```
=> Handle int for session value

src/NLog.Web.AspNetCore/AspNetExtensions.cs, src/NLog.Web.AspNetCore/Config/SetupExtensionsBuilderExtensions.cs
Reduce the level of confusion when used within `services.AddLogging()`-method. See also https://github.com/NLog/NLog/issues/4090
Like this:
```c#
services.AddLogging(loggingBuilder =>
{
loggingBuilder.ClearProviders();
loggingBuilder.AddNLogWeb(); // fix Missing serviceProvider, so no HttpContext
});
```
Instead of this:
```c#
services.AddLogging(loggingBuilder =>
{
loggingBuilder.ClearProviders();
loggingBuilder.AddNLog(provider => null);  // fix Missing serviceProvider, so no HttpContext
});
```
Guess when NLog.Extension.Logging ver. 2 with released with NLog ver. 5.0, then `AddNLog` can be marked as obsolete (Redirect to `AddNLogWeb`)
=> Introduced AddNLogWeb to avoid conflict with AddNLog from NLog.Extension.Logging

src/NLog.Web.AspNetCore/LayoutRenderers/AspNetUserClaimLayoutRenderer.cs, tests/NLog.Web.AspNetCore.Tests/AspNetUserClaimLayoutRendererTests.cs, tests/NLog.Web.AspNetCore.Tests/NLog.Web.AspNetCore.Tests.csproj
Example: `${aspnet-user-claim:ClaimTypes.Name}` . See also [ClaimTypes](https://docs.microsoft.com/en-us/dotnet/api/system.security.claims.claimtypes)-constants.
Not implemented for NLog.Web (MVC), since it requires NetFramework45.
=> Added support for HttpContext.User claim lookup using ${aspnet-user-claim}

src/NLog.Web.AspNetCore/NLog.Web.AspNetCore.csproj, src/NLog.Web/NLog.Web.csproj
=> Move to PackageIcon and PackageLicenseExpression for NuGet package

src/NLog.Web.AspNetCore/AspNetExtensions.cs
Allows one to do this:
var logFactory = new NLog.LogFactory.Setup()
.SetupExtensions(e => e.AutoLoadAssemblies(false))
.RegisterNLogWeb()
.LoadConfigurationFromFile("nlog.config", optional: false)
.LoadConfiguration(builder => builder.LogFactory.AutoShutdown = false).LogFactory;
builder.UseStartup<Startup>()
.ConfigureLogging((ctx, logging) =>
{
logging.ClearProviders();
logging.SetMinimumLevel(Microsoft.Extensions.Logging.LogLevel.Debug);
logging.AddNLogWeb(logFactory, new NLogAspNetCoreOptions() { ShutdownOnDispose = true });
});
So the MEL receives an isolated LogFactory, that is fully initialised (Instead of using the global NLog.LogManager).
=> Add AddNLogWeb with NLog LogFactory and NLogAspNetCoreOptions for better isolation

src/NLog.Web.AspNetCore/LayoutRenderers/AspNetUserClaimLayoutRenderer.cs, src/Shared/Internal/HttpContextExtensions.cs, src/Shared/LayoutRenderers/AspNetLayoutRendererBase.cs, src/Shared/LayoutRenderers/AspNetRequestUrlRenderer.cs, src/Shared/LayoutRenderers/AspNetUserAuthTypeLayoutRenderer.cs, src/Shared/LayoutRenderers/AspNetUserIdentityLayoutRenderer.cs, src/Shared/LayoutRenderers/AspNetUserIsAuthenticatedLayoutRenderer.cs
Suppresses `ObjectDisposedException` when HttpContext is no longer active (Avoid crashing when NLog users are wrongly using `ThrowExceptions=true`). Usually caused by NLog-users scheduling work on background-thread that is not awaited so it is runnng after HttpRequest has completed.
Alternative workaround to awaiting the background-task is to suppress the capture of thread-execution-context, so the HttpContext doesn't travel to the background-thread:
```c#
using (ExecutionContext.SuppressFlow())
{
Task.Run(() => {});
}
```
The correct way of handling this is to ensure logging from non-awaited background-tasks doesn't reach Layout-logic that includes `${aspnet-request}`-Layout-logic (Redirect to NLog targets with simple Layout-logic).
=> HttpContext - Extended ObjectDisposedException handling

src/Shared/LayoutRenderers/AssemblyVersionLayoutRenderer.cs, tests/Shared/LayoutRenderers/AssemblyVersionLayoutRendererTests.cs, tests/Shared/LayoutRenderers/TestInvolvingAspNetHttpContext.cs
Trying to fix bug #633 on ASP.NET that was introduced with #305 (But not made better by #326)
Special hack implemented, since class-attributes are inherited and cannot be removed again.
Added unit-test to prove the fix is working.
=> Remove ThreadAgnostic from AssemblyVersionLayoutRenderer when ASP.NET

src/Shared/LayoutRenderers/AssemblyVersionLayoutRenderer.cs
Rename to FixThreadAgnostic. And moved InternalLogger to `InitializeLayoutRenderer` (instead of every write)
Followup to #634
=> Fix AssemblyVersionLayoutRenderer on ASP.NET to work with async=true

src/NLog.Web.AspNetCore/NLog.Web.AspNetCore.csproj, src/NLog.Web.AspNetCore/readme.txt, src/NLog.Web/NLog.Web.csproj, src/NLog.Web/readme.txt
=> Added readme.txt for the NuGet packages

src/NLog.Web.AspNetCore/AspNetExtensions.cs, tests/NLog.Web.AspNetCore.Tests/AspNetCoreTests.cs
Followup to https://github.com/NLog/NLog.Extensions.Logging/pull/482 that resolves #646
=> NLogAspNetCoreOptions - Added ReplaceLoggerFactory and RemoveLoggerFactoryFilter

examples/ASP.NET Core 2/Visual Studio 2017/ASP.NET Core 2 - VS2017/Program.cs, src/Shared/LayoutRenderers/AspNetLayoutRendererBase.cs, src/Shared/LayoutRenderers/NLogWebLayoutRenderer.cs, tests/Shared/RegisterCustomLayoutRenderer.cs
Introduced NLogWebLayoutRenderer for caching of IHttpContextAccessor
Plus some spelling fixes
Fixes https://github.com/NLog/NLog.Web/issues/632
=> AspNetLayoutRendererBase.Register should cache IHttpContextAccessor

src/NLog.Web.AspNetCore/AspNetExtensions.cs
=> Updated xml-docs for AddNLog-methods to instead use AddNLogWeb

README.md, src/NLog.Web.AspNetCore/AspNetExtensions.cs, src/NLog.Web.AspNetCore/Config/SetupBuilderExtensions.cs, src/NLog.Web.AspNetCore/LayoutRenderers/AspNetEnvironmentLayoutRenderer.cs, src/NLog.Web.AspNetCore/NLog.Web.AspNetCore.csproj, src/Shared/Internal/HttpContextExtensions.cs, src/Shared/LayoutRenderers/AspNetAppBasePathLayoutRenderer.cs, src/Shared/LayoutRenderers/AspNetRequestPostedBody.cs, src/Shared/LayoutRenderers/AspNetWebRootPathLayoutRenderer.cs, src/Shared/LayoutRenderers/IISInstanceNameLayoutRenderer.cs, tests/NLog.Web.AspNetCore.Tests/AspNetCoreTests.cs, tests/NLog.Web.AspNetCore.Tests/NLog.Web.AspNetCore.Tests.csproj, tests/Shared/TestBase.cs
=> Drop support ASP.NET Core 1

examples/ASP.NET Core 3/ASP.NET Core 3 - VS2019/NLog.config, examples/ASP.NET Core 5/ASP.NET Core 5 NLog Example/nlog.config, src/NLog.Web/Config/SetupBuilderExtensions.cs, src/NLog.Web/Config/SetupExtensionsBuilderExtensions.cs, tests/NLog.Web.Tests/AspNetTests.cs, tests/Shared/RegisterCustomLayoutRenderer.cs
=> LogManager.Setup() - Support for RegisterNLogWeb + RegisterAspNetLayoutRenderer

src/NLog.Web/LayoutRenderers/AspNetApplicationValueLayoutRenderer.cs, src/Shared/LayoutRenderers/AspNetItemValueLayoutRenderer.cs, src/Shared/LayoutRenderers/AspNetRequestDurationLayoutRenderer.cs, src/Shared/LayoutRenderers/AspNetSessionValueLayoutRenderer.cs, tests/NLog.Web.Tests/LayoutRenderers/AspNetApplicationValueLayoutRendererTests.cs, tests/Shared/LayoutRenderers/AspNetItemValueLayoutRendererTests.cs
=> Changed format Culture to InvariantCulture to match default NLog Culture

src/NLog.Web.AspNetCore/NLogRequestLoggingMiddleware.cs, src/NLog.Web.AspNetCore/NLogRequestLoggingOptions.cs, src/NLog.Web/NLogRequestLoggingModule.cs, src/Shared/Layouts/W3CExtendedLogField.cs
Alternative one can use when-filters in the NLog LoggingRules, but ExcludeRequestPaths is faster
=> NLogRequestLogging - Added DurationThresholdMs + ExcludeRequestPaths

src/NLog.Web.AspNetCore/AspNetExtensions.cs
=> Include ContentRootPath when scanning for NLog.config candidate

src/NLog.Web.AspNetCore/NLog.Web.AspNetCore.csproj
=> Updated NetStandard2 + Net461 dependencies to fix warnings

CHANGELOG.MD, build.ps1, examples/ASP.NET 4.6.1/Visual Studio 2017/ASP.NET 4.6.1 - VS2017/packages.config, examples/ASP.NET Core 6/ASP.NET Core 6 NLog Example/ASP.NET Core 6 NLog Example.csproj, src/NLog.Web.AspNetCore/AspNetExtensions.cs, src/NLog.Web.AspNetCore/NLog.Web.AspNetCore.csproj, src/NLog.Web/NLog.Web.csproj, tests/NLog.Web.AspNetCore.Tests/AspNetCoreTests.cs
=> NLog 5.0 RTM

src/NLog.Web.AspNetCore/NLogRequestPostedBodyMiddleware.cs, src/NLog.Web/NLogRequestPostedBodyModule.cs, src/Shared/LayoutRenderers/AspNetRequestPostedBodyLayoutRenderer.cs, tests/NLog.Web.Tests/NLogRequestPostedBodyModuleTests.cs
Matching #783 but with HttpModule for ASP.NET Classic.
=> NLogRequestPostedBodyModule - Enables ${aspnet-request-posted-body}

src/Shared/LayoutRenderers/AspNetRequestIsWebSocketLayoutRenderer.cs, tests/Shared/LayoutRenderers/AspNetRequestIsWebSocketLayoutRendererTests.cs
=> AspNetRequestIsWebSocketLayoutRenderer - Changed from true / false to 1 / 0

src/NLog.Web/Internal/HttpCookieCollectionValues.cs, src/Shared/LayoutRenderers/AspNetRequestCookieLayoutRenderer.cs, src/Shared/LayoutRenderers/AspNetResponseCookieLayoutRenderer.cs, tests/Shared/LayoutRenderers/AspNetRequestWebSocketRequestedProtocolsLayoutRendererTests.cs
And removed `ToList()`-calls and reduced enumerator-allocations and removed sequential-scanning with `SingleOrDefault`
=> AspNetRequestCookieLayoutRenderer + AspNetResponseCookieLayoutRenderer with better code-reuse

src/NLog.Web.AspNetCore/NLogAspNetCoreOptions.cs
Discovered that the Microsoft Host disposes the LoggerFactory on startup-exception, so any logging after that point will be lost. See also https://github.com/dotnet/runtime/issues/72225 
Instead it is better to explicit call NLog.LogManager.Shutdown(), so the NLog Logger is still works when logging the exception.
Reverting #691
=> Reverted default value for ShutdownOnDispose to false

src/Shared/Internal/ReEntrantScopeLock.cs, src/Shared/LayoutRenderers/AspNetSessionIdLayoutRenderer.cs, src/Shared/LayoutRenderers/AspNetSessionValueLayoutRenderer.cs
Followup to #850 (Moved session-lookup so it is protected by the ReEntrant-Scope-Lock )
=> AspNetSessionValueLayoutRenderer - Skip ReEntrantScopeLock for classic NLog.Web

src/Shared/Enums/AspNetRequestUrlProperty.cs, src/Shared/LayoutRenderers/AspNetRequestUrlRenderer.cs, tests/Shared/LayoutRenderers/AspNetRequestUrlRendererTests.cs
=> aspnet-request-url - change to property-enum instead of booleans

src/NLog.Web.AspNetCore/AspNetExtensions.cs, src/NLog.Web.AspNetCore/Config/SetupBuilderExtensions.cs
Followup to #878 and https://github.com/NLog/NLog.Extensions.Logging/pull/632
=> Use RegisterConfigSettings instead of ConfigSettingLayoutRenderer

src/NLog.Web.AspNetCore/Config/SetupBuilderExtensions.cs, src/Shared/LayoutRenderers/AspNetAppBasePathLayoutRenderer.cs, tests/Shared/LayoutRenderers/AspNetAppBasePathLayoutRendererTests.cs
Matching #885 partial reverting #760
=> Changed AspNetAppBasePathLayoutRenderer  to prioritize current directory

src/Shared/LayoutRenderers/AspNetAppBasePathLayoutRenderer.cs
=> Changed AspNetAppBasePathLayoutRenderer  to prioritize current directory (code layout)

src/Shared/LayoutRenderers/AspNetMvcActionRenderer.cs, src/Shared/LayoutRenderers/AspNetMvcControllerRenderer.cs, src/Shared/LayoutRenderers/AspNetRequestRouteParametersRenderer.cs, tests/NLog.Web.AspNetCore.Tests/LayoutRenderers/AspNetRequestTlsHandshakeLayoutRendererTests.cs, tests/NLog.Web.AspNetCore.Tests/LayoutRenderers/AspNetRequestTrackingConsentLayoutRendererTests.cs, tests/Shared/LayoutRenderers/AspNetMvcActionRendererTests.cs, tests/Shared/LayoutRenderers/AspNetMvcControllerRendererTests.cs, tests/Shared/LayoutRenderers/AspNetRequestRouteParametersRendererTests.cs, tests/Shared/LayoutRenderers/AspNetSessionIDLayoutRendererTests.cs, tests/Shared/LayoutRenderers/AspNetSessionValueLayoutRendererTests2.cs, tests/Shared/LayoutRenderers/LayoutRenderersTestBase.cs
Optimizing:
- AspNetMvcActionRenderer - `${aspnet-mvc-action}`
- AspNetMvcControllerRenderer - `${aspnet-mvc-controller}`
- AspNetRequestRouteParametersRenderer - `${aspnet-request-routeparameters}`
=> Skip allocating RouteData when only need to lookup single value

src/Shared/Internal/PropertyReader.cs, src/Shared/LayoutRenderers/AspNetItemValueLayoutRenderer.cs, tests/Shared/LayoutRenderers/AspNetItemValueLayoutRendererTests.cs
Changed as little code as possible, added 2 new unit tests
=> Add ObjectPath to AspNetItemValueLayoutRenderer

src/NLog.Web/DefaultHttpContextAccessor.cs, src/Shared/Internal/HttpContextExtensions.cs, src/Shared/LayoutRenderers/AspNetLayoutRendererBase.cs
Reducing the overhead of AspNetLayoutRendererBase before making it obsolete with #846
=> AspNetLayoutRendererBase - Skip allocating extra HttpContextWrapper

src/NLog.Web/NLogHttpModule.cs, src/Shared/Targets/Wrappers/AspNetBufferingTargetWrapper.cs, tests/Shared/Targets/AspNetBufferingTargetWrapperTests.cs
Follow up to #900 (Avoid breaking changes)
=> AspNetBufferingTargetWrapper - Use NLogHttpModule EventHandler like before

src/Shared/LayoutRenderers/AspNetRequestQueryStringLayoutRenderer.cs, tests/Shared/LayoutRenderers/AspNetQueryStringLayoutRendererTests.cs
Consistent with the other LayoutRenders that inherits from AspNetLayoutMultiValueRendererBase (And can print all items)
=> AspNetQueryStringLayoutRenderer - Added Exclude option

src/Shared/LayoutRenderers/AspNetResponseStatusCodeRenderer.cs, tests/Shared/LayoutRenderers/AspNetResponseStatusCodeRendererTests.cs
Follow up to  #921 with reduced string-allocation on all platforms.
=> AspNet Response HttpStatusCode LayoutRenderer as Enum.ToString

src/Shared/LayoutRenderers/AspNetRequestIpLayoutRenderer.cs, tests/Shared/LayoutRenderers/AspNetRequestIpLayoutRendererTests.cs
At the firm I work for, the network engineers have not followed X-Forwarded-For HHTP headers standards.
Instead of having the desired client IP at the start of the list of IP addresses in the header, the client IP is the second or third element, depending upon whether you are in development, test, or production network.
One way to solve this is to add an int Index property to the layout renderer.
=> Handle malformed X-Forwarded-For Header

src/NLog.Web.AspNetCore/LayoutRenderers/AspNetRequestEndPointLayoutRenderer.cs, src/Shared/Internal/HttpContextExtensions.cs, src/Shared/LayoutRenderers/AspNetRequestUrlRenderer.cs, tests/NLog.Web.AspNetCore.Tests/LayoutRenderers/AspNetRequestEndPointLayoutRendererTests.cs, tests/Shared/LayoutRenderers/AspNetSessionValueLayoutRendererTests.cs
Wiki: https://github.com/NLog/NLog/wiki/AspNet-Request-EndPoint-Layout-Renderer
=> aspnet-request-endpoint - EndPoint Routing DisplayName

src/NLog.Web.AspNetCore/NLogRequestPostedBodyMiddleware.cs, tests/NLog.Web.AspNetCore.Tests/NLogRequestPostedBodyMiddlewareTests.cs
Resolves  #956. Fixes bug introduced with #933
=> NLogRequestPostedBodyMiddleware - Fixed handling of Stream.CanSeek

src/NLog.Web.AspNetCore/NLogRequestPostedBodyMiddleware.cs, tests/NLog.Web.AspNetCore.Tests/NLogRequestPostedBodyMiddlewareTests.cs
```
System.NotSupportedException: Specified method is not supported.
at Microsoft.AspNetCore.Server.IIS.Core.ReadOnlyStream.get_Position()
at Microsoft.AspNetCore.Server.IIS.Core.WrappingStream.get_Position()
at NLog.Web.NLogRequestPostedBodyMiddleware.ShouldCaptureRequestBody(HttpContext context)
at NLog.Web.NLogRequestPostedBodyMiddleware.Invoke(HttpContext context)
at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext ontext)
at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, waggerProvider swaggerProvider)
at Microsoft.AspNetCore.HttpLogging.HttpLoggingMiddleware.InvokeInternal(HttpContext context)
at …
```
=> NLogRequestPostedBodyMiddleware - Fixed handling of Stream.Position

CHANGELOG.MD, build.ps1, examples/ASP.NET 4.6.1/Visual Studio 2017/ASP.NET 4.6.1 - VS2017/packages.config, src/NLog.Web.AspNetCore/NLog.Web.AspNetCore.csproj, src/NLog.Web/NLog.Web.csproj
- NLog v5.2.2 - https://github.com/NLog/NLog/releases/tag/v5.2.2
- NLog.Extensions.Logging v5.3.2 - https://github.com/NLog/NLog.Extensions.Logging/releases/tag/v5.3.2
=> Version 5.3.2

NLog.Web.sln, tests/NLog.Web.AspNetCore.Tests/NLog.Web.AspNetCore.Tests.csproj
To fix Azure DevOps that complains about NetCoreApp3.1
`Testhost process for source(s) 'D:\a\1\s\tests\NLog.Web.AspNetCore.Tests\bin\Release\netcoreapp3.1\NLog.Web.AspNetCore.Tests.dll' exited with error: You must install or update .NET to run this application.`
=> Update unit-test-projects to net6

src/Shared/LayoutRenderers/AspNetUserClaimLayoutRenderer.cs, tests/Shared/LayoutRenderers/AspNetUserClaimLayoutRendererTests.cs
I finally got to work on it today after 6 weeks.  Please let me know if this is an accurate answer to the link in the issue.
Resolves #949
=> Extended AspNetUserClaimLayoutRenderer to handle multi-values

src/NLog.Web.AspNetCore/NLogBufferingTargetWrapperMiddleware.cs, src/NLog.Web.AspNetCore/NLogRequestPostedBodyMiddleware.cs, src/NLog.Web/NLogHttpModule.cs, src/NLog.Web/NLogRequestPostedBodyModule.cs, src/Shared/LayoutRenderers/AspNetRequestPostedBodyLayoutRenderer.cs, src/Shared/Targets/Wrappers/AspNetBufferingTargetWrapper.cs
Uses ctor for middleware and httpmodule, and initializelayoutrender/initializetarget, instead of warning every time, as requested.
Resolves #954 and resolves #935
=> Issue 934 and 935, Middleware Initialization Debugging

CHANGELOG.MD, appveyor.yml, build.ps1, examples/ASP.NET 4.6.1/Visual Studio 2017/ASP.NET 4.6.1 - VS2017/ASP.NET 4.6.1 - VS2017.csproj, examples/ASP.NET 4.6.1/Visual Studio 2017/ASP.NET 4.6.1 - VS2017/packages.config, src/NLog.Web.AspNetCore/NLog.Web.AspNetCore.csproj, src/NLog.Web/NLog.Web.csproj
- NLog v5.2.5 - https://github.com/NLog/NLog/releases/tag/v5.2.5
- NLog.Extensions.Logging v5.3.5 - https://github.com/NLog/NLog.Extensions.Logging/releases/tag/v5.3.5
=> Version 5.3.5

CHANGELOG.MD, examples/ASP.NET 4.6.1/Visual Studio 2017/ASP.NET 4.6.1 - VS2017/ASP.NET 4.6.1 - VS2017.csproj, examples/ASP.NET 4.6.1/Visual Studio 2017/ASP.NET 4.6.1 - VS2017/packages.config, src/NLog.Web.AspNetCore/NLog.Web.AspNetCore.csproj, src/NLog.Web/NLog.Web.csproj
- NLog v5.2.8 - https://github.com/NLog/NLog/releases/tag/v5.2.8
- NLog.Extensions.Logging v5.3.8 - https://github.com/NLog/NLog.Extensions.Logging/releases/tag/v5.3.8
=> Version 5.3.8

CHANGELOG.MD, appveyor.yml, build.ps1, examples/ASP.NET 4.6.1/Visual Studio 2017/ASP.NET 4.6.1 - VS2017/ASP.NET 4.6.1 - VS2017.csproj, examples/ASP.NET 4.6.1/Visual Studio 2017/ASP.NET 4.6.1 - VS2017/packages.config, src/NLog.Web.AspNetCore/AspNetExtensions.cs, src/NLog.Web.AspNetCore/NLog.Web.AspNetCore.csproj, src/NLog.Web.AspNetCore/README.md, src/NLog.Web/NLog.Web.csproj, tests/NLog.Web.AspNetCore.Tests/NLog.Web.AspNetCore.Tests.csproj, tests/NLog.Web.Tests/NLog.Web.Tests.csproj, tests/Shared/LayoutRenderers/W3CLoggerLayoutTests.cs
- NLog v5.3.1 - https://github.com/NLog/NLog/releases/tag/v5.3.1
- NLog.Extensions.Logging v5.3.9 - https://github.com/NLog/NLog.Extensions.Logging/releases/tag/v5.3.9
=> Version 5.3.9

src/Shared/LayoutRenderers/AspNetRequestUrlRenderer.cs
Allows you to write: `${aspnet-request-url:Port}`
=> AspNetRequestUrlRenderer - Mark Properties-option as DefaultParameter

tests/NLog.Web.AspNetCore.Tests/AspNetCoreTests.cs
Resolves #1056 - Followup to #1060
=> UseNLog should fallback after checking ContentRoot for NLog.config (test)

src/NLog.Web.AspNetCore/AspNetExtensions.cs, src/NLog.Web.AspNetCore/Config/SetupBuilderExtensions.cs, tests/NLog.Web.AspNetCore.Tests/AspNetCoreTests.cs
Use `LoadConfigurationFromFile` instead of explicit creating `XmlLoggingConfiguration` for better NLog InternalLogger output.
=> UseNLog allow fallback to only EnvironmentName for NLog config

src/NLog.Web.AspNetCore/AspNetExtensions.cs, src/Shared/LayoutRenderers/AspNetResponseHasStartedLayoutRenderer.cs, src/Shared/LayoutRenderers/AspNetUserClaimLayoutRenderer.cs
=> Remove unused method LoadXmlLoggingConfigurationFromPath

CHANGELOG.MD, appveyor.yml, build.ps1, examples/ASP.NET 4.6.1/Visual Studio 2017/ASP.NET 4.6.1 - VS2017/ASP.NET 4.6.1 - VS2017.csproj, examples/ASP.NET 4.6.1/Visual Studio 2017/ASP.NET 4.6.1 - VS2017/packages.config, src/NLog.Web.AspNetCore/NLog.Web.AspNetCore.csproj, src/NLog.Web/NLog.Web.csproj, tests/NLog.Web.AspNetCore.Tests/NLog.Web.AspNetCore.Tests.csproj
- NLog v5.4 - https://github.com/NLog/NLog/releases/tag/v5.4.0
- NLog.Extensions.Logging v5.4 - https://github.com/NLog/NLog.Extensions.Logging/releases/tag/v5.4.0
=> Version 5.4
