NLog/NLog.Web

- NLog.Web.Tests/LayoutRenderers/AspNetSessionValueLayoutRendererTests.cs
- NLog.Web/Internal/PropertyReader.cs
- NLog.Web/LayoutRenderers/AspNetItemValueLayoutRenderer.cs
- NLog.Web/LayoutRenderers/AspNetSessionValueLayoutRenderer.cs
- NLog.Web/NLog.Web.csproj
- README.md
Supersedes #11 
Fixed code duplication, added unit tests.
Thanks @dafanasiev  for the initial PR.
> Aspnet-item renderer

- NLog.Web.Tests/LayoutRenderers/AspNetSessionValueLayoutRendererTests.cs
- NLog.Web.Tests/NLog.Web.Tests.csproj
- NLog.Web.Tests/packages.config
- NLog.Web/NLog.Web.csproj
- NLog.Web/packages.config
Needed NLog 4.0.1 for that (auto-load fix). Unclear why it worked in mstest
> MsTest  => xUnit2

- NLog.Web.ASPNET5/AspNetExtensions.cs
- NLog.Web.ASPNET5/Internal/ServiceLocator.cs
- NLog.Web.ASPNET5/LayoutRenderers/AspNetApplicationValueLayoutRenderer.cs
- NLog.Web.ASPNET5/LayoutRenderers/AspNetItemValueLayoutRenderer.cs
- NLog.Web.ASPNET5/LayoutRenderers/AspNetLayoutRendererBase.cs
- NLog.Web.ASPNET5/LayoutRenderers/AspNetRequestValueLayoutRenderer.cs
- NLog.Web.ASPNET5/LayoutRenderers/AspNetSessionValueLayoutRenderer.cs
- NLog.Web.ASPNET5/LayoutRenderers/AspNetUserAuthTypeLayoutRenderer.cs
- NLog.Web.ASPNET5/LayoutRenderers/AspNetUserIdentityLayoutRenderer.cs
- NLog.Web.ASPNET5/LayoutRenderers/IISInstanceNameLayoutRenderer.cs
- NLog.Web.ASPNET5/project.json
> Fix aspnet5

- README.md
> Update README for aspnet5

- NLog.Web/NLog.Web.nuspec
- appveyor.yml
- build_aspnet4.bat
- build_aspnet5.bat
create both nupkg (aspnet4 + aspnet5), move build scripts to .bat files
restore and update nuspec
> Package both nupkg + build scripts

- NLog.Web.AspNetCore/AspNetExtensions.cs
- NLog.Web.AspNetCore/global.json
- NLog.Web.AspNetCore/project.json
- NLog.Web.AspNetCore/project.lock.json
Upgrade RC2 to RTM. .Net Core.
> Upgrade RC2 to RTM. .Net Core.

- README.md
> Readme - make core vs non-core clearer

- NLog.Web.AspNetCore.Tests/LayoutRenderers/AspNetRequestValueLayoutRendererTests.cs
- NLog.Web.AspNetCore.Tests/project.json
- NLog.Web.AspNetCore.Tests/project.lock.json
- NLog.Web.AspNetCore/global.json
- NLog.Web.AspNetCore/project.json
- NLog.Web.AspNetCore/project.lock.json
- NLog.Web/NLog.Web.csproj
- NLog.Web/packages.NLog.Web.config
- appveyor.yml
Needed for Collection support (in targets) in NLog.4.4
fixes #77, Fixes #72, fixes #62
> Upgrade to NLog 4.4

- NLog.Web.AspNetCore/Internal/PropertyReader.cs
- NLog.Web.AspNetCore/LayoutRenderers/AspNetItemValueLayoutRenderer.cs
- NLog.Web.AspNetCore/LayoutRenderers/AspNetRequestValueLayoutRenderer.cs
- NLog.Web.AspNetCore/LayoutRenderers/AspNetSessionIDLayoutRenderer.cs
- NLog.Web.AspNetCore/LayoutRenderers/AspNetSessionValueLayoutRenderer.cs
Fixes https://github.com/NLog/NLog.Web/issues/69
fixes #70
> added null checks

- NLog.Web.AspNetCore.Tests/project.lock.json
- NLog.Web.AspNetCore/AspNetExtensions.cs
- NLog.Web.AspNetCore/project.json
- NLog.Web.AspNetCore/project.lock.json
reference  nlog.extensions.logging & asp.net-core
> Move ASP.NET helpers from nlog.extensions.logging, 

- NLog.Web.AspNetCore/project.json
Fixes https://github.com/NLog/NLog.Extensions.Logging/issues/96
> Update dependencies and version number

- NLog.Web.AspNetCore/LayoutRenderers/Class.cs
Fixes https://github.com/NLog/NLog.Web/issues/92
> Add ${aspnet-traceidentifier} (ASP.NET Core only)

- NLog.Web/Properties/AssemblyInfo.cs
> Update assemblyinfo & strong name version to 4.0.0.0

- NLog.Web.Tests/NLog.Web.Tests.csproj
- NLog.Web.Tests/packages.NLog.Web.Tests.config
- NLog.Web/NLog.Web.csproj
- NLog.Web/packages.NLog.Web.config
- appveyor.yml
fixes https://github.com/NLog/NLog.Web/issues/102
> Update nlog version

- NLog.Web.AspNetCore.sln
> Fix SLN file

- NLog.Web.AspNetCore/LayoutRenderers/AspNetRequestIpLayoutRenderer.cs
- NLog.Web/NLog.Web.csproj
> Added ${aspnet-request-ip}

- NLog.Web.AspNetCore/LayoutRenderers/AspNetRequestUrlRenderer.cs
- NLog.Web.AspNetCore/NLog.Web.AspNetCore.csproj
> Limit dependecies

- NLog.Web.AspNetCore/LayoutRenderers/AssemblyVersionLayoutRenderer.cs
Fixed comments for Name property (for .NET Full and Standard results of layout renderer will be different)
> Update AssemblyVersionLayoutRenderer docs for .NET core

- NLog.Web.AspNetCore/LayoutRenderers/AspNetLayoutRendererBase.cs
- appveyor.yml
- test_aspnet.bat
- test_aspnet.ps1
- test_aspnetcore.bat
- test_aspnetcore.ps1
fixing a bug that wasn't in production
> Fix error reporting, fix introduced bug

- NLog.Web.AspNetCore/NLog.Web.AspNetCore.csproj
- NLog.Web.AspNetCore/Properties/AssemblyInfo.cs
- NLog.Web/NLog.Web.csproj
- NLog.Web/Properties/AssemblyInfo.cs
- appveyor.yml
And fixed FileVersion so resolves #147
> Removed System.ValueTuple as dependency for .NET Core app 1, add file version to assembly

- NLog.Web.AspNetCore/LayoutRenderers/AspNetAppBasePathLayoutRenderer.cs
- NLog.Web.AspNetCore/LayoutRenderers/AspNetEnvironmentLayoutRenderer.cs
- NLog.Web.AspNetCore/LayoutRenderers/AspNetWebRootPathLayoutRenderer.cs
- NLog.Web/NLog.Web.csproj
- examples/ASP.NET Core 2/Visual Studio 2017/ASP.NET Core 2 - VS2017/NLog.config
- examples/ASP.NET Core 2/Visual Studio 2017/ASP.NET Core 2 - VS2017/Program.cs
- examples/ASP.NET Core 2/Visual Studio 2017/ASP.NET Core 2 - VS2017/appsettings.Development.json
- examples/ASP.NET Core 2/Visual Studio 2017/ASP.NET Core 2 - VS2017/appsettings.json
Also updated wiki-page to match this commit:
https://github.com/NLog/NLog.Web/wiki/Getting-started-with-ASP.NET-Core-2
Resolves #225
> ASP.NET Core2 Example - Updated blackhole configuration + ${aspnet-appbasepath} + ${aspnet-webrootpath}

- NLog.Web.AspNetCore/LayoutRenderers/AspNetRequestIpLayoutRenderer.cs
> ${aspnet-request-ip} handle emtpy Request on HttpContext

- CHANGELOG.MD
- NLog.Web.AspNetCore/NLog.Web.AspNetCore.csproj
Related: https://github.com/NLog/NLog.Extensions.Logging/issues/216
fixes: #286
> Update NLog dependency, release 4.5.4 (ASP.NET Core)

- NLog.Web.AspNetCore/LayoutRenderers/AspNetLayoutRendererBase.cs
> HttpContextAccessor - Improve error-handling during startup / shutdown

- NLog.Web.AspNetCore/NLog.Web.AspNetCore.csproj
Waiting for release https://github.com/NLog/NLog.Extensions.Logging/pull/228
> Update NLog.Extensions.Logging Dependency

- NLog.Web.AspNetCore.Tests/LayoutRenderers/AspNetSessionValueLayoutRendererTests.cs
- NLog.Web.AspNetCore.Tests/LayoutRenderers/AspNetSessionValueLayoutRendererTests2.cs
> Added AspNetSessionValueLayoutRendererTests for asp.net core

- appveyor.yml
> Add NUGET_DEPLOY_SECRET

- examples/ASP.NET 4.6.1/Visual Studio 2017/ASP.NET 4.6.1 - VS2017/NLog.config
- examples/ASP.NET Core 2/Visual Studio 2017/ASP.NET Core 2 - VS2017/NLog.config
Removed AssemblyVersionLayoutRenderer debug code
> Fixed NLog.config in example projects

- tests/NLog.Web.AspNetCore.Tests/NLog.Web.AspNetCore.Tests.csproj
https://github.com/NuGet/Home/issues/7414#issuecomment-472561481
fixes https://github.com/NLog/NLog.Web/issues/354
> Get rid of NU3005 error

- tests/Shared/LayoutRenderers/AspNetSessionValueLayoutRendererTests.cs
replaced fakes with isolated mocks
> Improve stability of session unit tests

- NLog.Web.sln.DotSettings
- tests/NLog.Web.AspNetCore.Tests/AspNetCoreTests.cs
- tests/NLog.Web.AspNetCore.Tests/NLog.Web.AspNetCore.Tests.csproj
- tests/NLog.Web.Tests/DefaultHttpContextAccessorTests.cs
- tests/Shared/FakeHttpContextAccessor.cs
- tests/Shared/LayoutRenderers/AspNetRequestPostedBodyTests.cs
- tests/Shared/LayoutRenderers/AssemblyVersionLayoutRendererTests.cs
- tests/Shared/RegisterCustomLayoutRenderer.cs
- tests/Shared/TestBase.cs
> Make namespaces in test projects consistent

- src/NLog.Web.AspNetCore/NLog.Web.AspNetCore.csproj
Revert as 2.1 is LTS. Also added note
> Revert update microsoft.asp net core

- src/Shared/LayoutRenderers/AspNetRequestCookieLayoutRenderer.cs
- src/Shared/LayoutRenderers/AspNetRequestFormLayoutRenderer.cs
- tests/Shared/LayoutRenderers/AspNetCookieLayoutRendererTests.cs
Updated Microsoft.AspNetCore dependencies to Long Term Support versions
See also: https://dotnet.microsoft.com/platform/support/policy/dotnet-core
> AspNetRequestCookieLayoutRenderer - Added support for Exclude

- src/NLog.Web.AspNetCore/AspNetExtensions.cs
Matching https://github.com/NLog/NLog.Extensions.Logging/pull/345
> Added AddNLog with functor to create/initialize LogFactory for NLogLoggingProvider

- src/NLog.Web.AspNetCore/AspNetExtensions.cs
Updated to match:
https://github.com/NLog/NLog.Extensions.Logging/pull/393
https://github.com/NLog/NLog.Extensions.Logging/pull/407
> Improved AddNLog with LoggingConfiguration to handle custom LogFactory

- appveyor.yml
Will publish nuget-packages when merged.
> NLog.Web.AspNetCore ver. 4.9.1

- src/Shared/LayoutRenderers/AspNetRequestUrlRenderer.cs
- tests/Shared/LayoutRenderers/AspNetRequestUrlRendererTests.cs
implements #529
See https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.http.features.ihttprequestfeature.rawtarget
> ${aspnet-request-url} Added UseRawTarget option

- src/Shared/LayoutRenderers/AspNetRequestIpLayoutRenderer.cs
- tests/Shared/LayoutRenderers/AspNetRequestIpLayoutRendererTests.cs
> ${aspnet-request-ip}: make ForwardedForHeader configurable

- examples/ASP.NET Core 3/ASP.NET Core 3 - VS2019/NLog.config
> Updated example NLog.config to include logging of hosting lifetime messages

- build_aspnet.bat
- src/NLog.Web.AspNetCore/NLog.Web.AspNetCore.csproj
- src/NLog.Web/NLog.Web.csproj
See https://github.com/clairernovotny/DeterministicBuilds
and https://github.com/NLog/NLog.Extensions.Logging/pull/479
> Enable deterministic build

- src/NLog.Web.AspNetCore/AspNetExtensions.cs
- src/NLog.Web.AspNetCore/NLog.Web.AspNetCore.csproj
- src/NLog.Web/NLog.Web.csproj
- tests/NLog.Web.AspNetCore.Tests/AspNetCoreTests.cs
Resolves #661, see also https://github.com/NLog/NLog.Extensions.Logging/pull/501
> Added support for option LoggingConfigurationSectionName

- CHANGELOG.MD
- NLog.Web.sln
- appveyor.yml
- build.ps1
- src/NLog.Web.AspNetCore/NLog.Web.AspNetCore.csproj
Users have started to notice `LoggingConfigurationSectionName`, best to complete the circle.
> Version 4.13

- src/NLog.Web.AspNetCore/AspNetExtensions.cs
- src/Shared/LayoutRenderers/AspNetRequestPostedBody.cs
> ASP_NET_CORE2 is now the odd one

- src/NLog.Web.AspNetCore/AspNetExtensions.cs
- src/NLog.Web.AspNetCore/NLogAspNetCoreOptions.cs
> NLogAspNetCoreOptions - Enable ShutdownOnDispose by default

- src/Shared/LayoutRenderers/AspNetLayoutMultiValueRendererBase.cs
Little confusing to have that as default parameter.
> AspNetLayoutMultiValueRendererBase - Removed DefaultParameter from OutputFormat

- src/Shared/LayoutRenderers/AspNetLayoutRendererBase.cs
- src/Shared/LayoutRenderers/NLogWebFuncLayoutRenderer.cs
- tests/Shared/RegisterCustomLayoutRenderer.cs
And removed some global state in unit-test (to make them more stable)
> Renamed NLogWebLayoutRenderer to NLogWebFuncLayoutRenderer

- src/Shared/LayoutRenderers/AspNetRequestRouteParametersRenderer.cs
- tests/Shared/LayoutRenderers/AspNetRequestRouteParametersRendererTests.cs
Basically "just" the code from this issue: https://github.com/NLog/NLog.Web/issues/576. But with support for ASP.NET too and some documentation.
> Added Layout renderer for ASP.NET Request route parameters

- src/NLog.Web.AspNetCore/Internal/ServiceLocator.cs
- src/NLog.Web.AspNetCore/LayoutRenderers/AspNetEnvironmentLayoutRenderer.cs
- src/Shared/LayoutRenderers/AspNetAppBasePathLayoutRenderer.cs
- src/Shared/LayoutRenderers/AspNetLayoutRendererBase.cs
- src/Shared/LayoutRenderers/AspNetWebRootPathLayoutRenderer.cs
- src/Shared/LayoutRenderers/IISInstanceNameLayoutRenderer.cs
- src/Shared/LayoutRenderers/NLogWebFuncLayoutRenderer.cs
Removed global static variables.
> AspNetLayoutRendererBase - Resolve IHttpContextAccessor using ServiceRepository

- build.ps1
- src/NLog.Web.AspNetCore/NLog.Web.AspNetCore.csproj
> Updated NetStandard2 + Net461 dependencies to fix warnings

- src/NLog.Web.AspNetCore/AspNetExtensions.cs
- src/Shared/LayoutRenderers/AspNetRequestHeadersLayoutRenderer.cs
- src/Shared/LayoutRenderers/AspNetRequestQueryStringLayoutRenderer.cs
- src/Shared/LayoutRenderers/AspNetRequestRouteParametersRenderer.cs
Between AspNetCore and AspNetClassic
> AspNetQueryStringLayoutRenderer - Reduce code duplication

- examples/ASP.NET Core 6/ASP.NET Core 6 NLog Example/ASP.NET Core 6 NLog Example.csproj
Must have been added by accident.
> Removed unnecessary dependency from ASP.NET Core 6 example project

- src/Shared/LayoutRenderers/AspNetResponseCookieLayoutRenderer.cs
> AspNetResponseCookieLayoutRenderer - Improved handling of empty properties with Verbose

- examples/ASP.NET Core 6/ASP.NET Core 6 NLog Example/nlog.config
> Updated NET6 example to use EventId instead of EventId_Id

- src/Shared/LayoutRenderers/AspNetLayoutMultiValueRendererBase.cs
- tests/Shared/LayoutRenderers/AspNetQueryStringLayoutRendererTests.cs
Fixed https://github.com/NLog/NLog.Web/issues/839
> Lowercase key aspnet render

- src/Shared/LayoutRenderers/AspNetLayoutMultiValueRendererBase.cs
> AspNetLayoutMultiValueRendererBase - LowerCaseKeys with less allocation

- src/NLog.Web.AspNetCore/LayoutRenderers/AspNetEnvironmentLayoutRenderer.cs
- src/Shared/LayoutRenderers/AspNetAppBasePathLayoutRenderer.cs
- src/Shared/LayoutRenderers/AspNetWebRootPathLayoutRenderer.cs
- src/Shared/LayoutRenderers/IISInstanceNameLayoutRenderer.cs
- tests/Shared/LayoutRenderers/AspNetWebRootPathLayoutRendererTests.cs
Followup to  #832 (Reusing `NLog.Web.Internal.IHostEnvironment` and align caching behavior)
> AspNetWebRootPathLayoutRenderer - Added unit-test

- tests/NLog.Web.AspNetCore.Tests/LayoutRenderers/AspNetEnvironmentLayoutRendererTests.cs
- tests/Shared/LayoutRenderers/AspNetAppBasePathLayoutRendererTests.cs
- tests/Shared/LayoutRenderers/AspNetWebRootPathLayoutRendererTests.cs
- tests/Shared/LayoutRenderers/IISInstanceNameLayoutRendererTests.cs
> AspNetWebRootPathLayoutRenderer - Added unit-test with parse and close

- CHANGELOG.MD
- build.ps1
- src/NLog.Web.AspNetCore/ILLink.Descriptors.xml
- src/NLog.Web.AspNetCore/NLog.Web.AspNetCore.csproj
- src/NLog.Web/NLog.Web.csproj
Fixing https://github.com/NLog/NLog/issues/5050
> Version 5.1.4

- src/NLog.Web.AspNetCore/Config/SetupBuilderExtensions.cs
Prepare for https://github.com/NLog/NLog.Extensions.Logging/pull/626
> LoadConfigurationFromAppSettings should always RegisterConfigSettings

- src/NLog.Web.AspNetCore/Config/SetupBuilderExtensions.cs
Trying to resolve #883, and partial reverting #763
> Changed LoadConfigurationFromAppSettings to prioritize current directory

- tests/Shared/Targets/AspNetBufferingTargetWrapperTests.cs
> AspNetBufferingTargetWrapperTests - Added testing of multiple http-contexts

- src/NLog.Web/NLogHttpModule.cs
- src/Shared/Targets/Wrappers/AspNetBufferingTargetWrapper.cs
> AspNetBufferingTargetWrapper - Skip HttpContextWrapper allocation

- src/Shared/Targets/Wrappers/AspNetBufferingTargetWrapper.cs
Followup to #900 (fix registration)
> AspNetBufferingTargetWrapper - Use NLogHttpModule EventHandler like before

- src/Shared/LayoutRenderers/AspNetUserClaimLayoutRenderer.cs
> AspNetUserClaimLayoutRenderer - Fixed code smells

- src/NLog.Web.AspNetCore/NLog.Web.AspNetCore.csproj
- src/Shared/LayoutRenderers/AspNetMvcActionRenderer.cs
- src/Shared/LayoutRenderers/AspNetMvcControllerRenderer.cs
- src/Shared/LayoutRenderers/AspNetMvcLayoutRendererBase.cs
- src/Shared/LayoutRenderers/AspNetRequestClientCertificateLayoutRenderer.cs
- tests/NLog.Web.AspNetCore.Tests/NLog.Web.AspNetCore.Tests.csproj
- tests/NLog.Web.Tests/NLog.Web.Tests.csproj
Avoid git-commit-hash as InformationalVersion suffix for test-library-project.
See also: https://github.com/dotnet/sdk/issues/37142
> Added IncludeSourceRevisionInInformationalVersion to fix InformationalVersion

- CHANGELOG.MD
- build.ps1
- examples/ASP.NET 4.6.1/Visual Studio 2017/ASP.NET 4.6.1 - VS2017/ASP.NET 4.6.1 - VS2017.csproj
- examples/ASP.NET 4.6.1/Visual Studio 2017/ASP.NET 4.6.1 - VS2017/packages.config
- src/NLog.Web.AspNetCore/NLog.Web.AspNetCore.csproj
- src/NLog.Web/NLog.Web.csproj
- tests/NLog.Web.AspNetCore.Tests/NLog.Web.AspNetCore.Tests.csproj
- tests/NLog.Web.Tests/NLog.Web.Tests.csproj
- NLog.Extensions.Logging v5.3.7 - https://github.com/NLog/NLog.Extensions.Logging/releases/tag/v5.3.7
> Version 5.3.7

- CHANGELOG.MD
- build.ps1
- src/NLog.Web.AspNetCore/NLog.Web.AspNetCore.csproj
- tests/NLog.Web.AspNetCore.Tests/AspNetCoreTests.cs
> Version 5.3.11

- CHANGELOG.MD
- appveyor.yml
- build.ps1
- src/NLog.Web.AspNetCore/AspNetExtensions.cs
- src/NLog.Web.AspNetCore/Config/SetupBuilderExtensions.cs
- src/NLog.Web.AspNetCore/NLog.Web.AspNetCore.csproj
Fixed bug introduced with #1012 + #1013 and restore behavior like #861
- NLog.Extensions.Logging v5.3.14 - https://github.com/NLog/NLog.Extensions.Logging/releases/tag/v5.3.14
> Version 5.3.14

- src/NLog.Web.AspNetCore/NLog.Web.AspNetCore.csproj
- tests/NLog.Web.AspNetCore.Tests/AspNetCoreTests.cs
> UseNLog should fallback after checking ContentRoot for NLog.config (test)

- CHANGELOG.MD
- build.ps1
- src/NLog.Web.AspNetCore/NLog.Web.AspNetCore.csproj
- NLog.Extensions.Logging v5.3.15 - https://github.com/NLog/NLog.Extensions.Logging/releases/tag/v5.3.15
> Version 5.3.15

- src/NLog.Web.AspNetCore/LayoutRenderers/AspNetRequestConnectionIdLayoutRenderer.cs
- src/Shared/LayoutRenderers/AspNetMvcActionLayoutRenderer.cs
- src/Shared/LayoutRenderers/AspNetMvcControllerLayoutRenderer.cs
- src/Shared/LayoutRenderers/AspNetRequestClientCertificateLayoutRenderer.cs
- src/Shared/LayoutRenderers/AspNetRequestIpLayoutRenderer.cs
Avoid checking `RouteTable` when no HttpContext. Followup to #1079
> Validate HttpContext before aspnet-mvc-action and aspnet-mvc-controller
